### ISSUE TITLE
TS won't complain about implicit any in composable declaration

### ISSUE THREAD

**Issue by danielweinmann** [seasonedcc/composable-functions#146]
Example:

![image](https://github.com/seasonedcc/composable-functions/assets/204765/046770d2-fb1e-48db-9589-79c947e18db4)

**Comment by gustavoguichard** [comment]
I don't get this bug, isn't it what [TS does by default](https://www.typescriptlang.org/play/?target=6#code/IYZwngdgxgBAZgV2gFwJYHsI2QJ2FAawCF1gcATAGVPIFNyAKAKBlZgG8YAHHdAK1pRkASXIwAvgBoWbAPSyYAPQD8M1rQgA3VLwgBbDcmlsY8paoCUHGTlrIEOLBAQAbF03FA)?

![Screenshot 2024-06-05 at 13 01 57](https://github.com/seasonedcc/composable-functions/assets/566971/caca8fb2-8f7a-4146-8bf2-38a3816a2ff2)

What are we aiming for here?
IMO you should type your parameters as you do with any function, but wrapping it in a `composable` will give ou composability and monadic error handling. When using `withSchema` on the other hand, the parameters will infer the type of the schema given earlier and if none is given then the parameters will be `unknown`.

**Comment by danielweinmann** [comment]
I want to have the same error I get when using strict TS inside of composable. Here's an example:

```ts
const foo = (bar) => bar
// ^ Error TS7006: Parameter bar implicitly has an any type.

const foo2 = composable((bar) => bar)
// ^ No error whatsoever
```

**Comment by gustavoguichard** [comment]
Fair enough... so the problem is not that it is `any` but the fact the lint isn't complaining, right?
I'll try to replicate to see what I can do about it

**Comment by diogob** [comment]
@gustavoguichard to be more precise, that is a TS error (no linting required).
