### ISSUE TITLE
Functions inside compositions allow for implicit any arguments

### ISSUE THREAD

**Issue by danielweinmann** [seasonedcc/composable-functions#165]
![Screenshot 2024-07-19 at 09 53 48](https://github.com/user-attachments/assets/20612948-b260-4825-9de2-fe56c6d963fd)

With `composable` outside a composition it gives an implicit-any error. Inside a composition, it does not. It also happens with regular functions not wrapped in composable:

![Screenshot 2024-07-19 at 09 51 07](https://github.com/user-attachments/assets/86aafd3c-1211-4cf3-9bf6-5b1658d2e16f)

**Comment by gustavoguichard** [comment]
This was probably introduced with 4.2... I think I'll have to add another layer of complexity to the combinators, at least I know what to do now 😅

**Comment by gustavoguichard** [comment]
Fixed on v4.4 ;)
