### ISSUE TITLE
Throw multiple input errors at once

### ISSUE THREAD

**Issue by diogob** [seasonedcc/composable-functions#22]
There are use cases such as [this one](https://github.com/SeasonedSoftware/remix-forms/issues/21), where throwing a single exception with multiple input errors is desirable. We should add a custom error constructor for that. Perhaps just have a plural `InputErrors` that will take a non-empty list as argument. If we are fine breaking backwards compatibility we could also just change the `InputError` type.

**Comment by danielweinmann** [comment]
I like the idea of having a separate error for this use case. The current InputError is very elegant for most use cases. It would be weird to have to pass a list to it.

**Comment by machour** [comment]
I'm also fine with having a separate `InputErrors` that would handle this case.

**Comment by diogob** [comment]
@machour I have just published the 0.3.0 to npm. The package.json from remix-forms is [bound to >= 0.2.0](https://github.com/SeasonedSoftware/remix-forms/blob/main/package.json#L37) so you should be able to update the remix-domains dependency on your project and use the new `InputErrors` error and pass a list of `{message: string, path: string}`.

The interface is described in the corresponding [README section](https://github.com/SeasonedSoftware/remix-domains#changing-the-errorresult-with-custom-errors).

**Comment by machour** [comment]
Tested and validated, thank you so much @diogob !

**Comment by gustavoguichard** [comment]
Just an update from the future! You can throw a list of errors now with:
```ts
const fn = composable(() => {
  throw new ErrorList([
    new Error('Oops'),
    new InputError('Required', ['name'])
  ])
})
```
