### ISSUE TITLE
Support for custom schema validators

### ISSUE THREAD

**Issue by marcus-sa** [seasonedcc/composable-functions#30]
Have you considered allowing developers to use custom schema validators?
I'd much rather use https://deepkit.io/library/type instead of https://zod.dev

**Comment by gustavoguichard** [comment]
This is duplicate of #36

**Comment by gustavoguichard** [comment]
Hey @marcus-sa !
Thank you for submitting the issue, sorry for closing it out prior to commenting, I'm testing this feature on my mobile's github app 😅

That said we don't plan to support custom serializers in the foreseeable feature - which may be the next major release.

It doesn't seem to be too hard to do it so we will keep an eye on "Type" and this sort of request tho.

Is there any specific reason you'd use one over another? Do you have any API suggestions?

Cheers

**Comment by gustavoguichard** [comment]
Hey @marcus-sa and @FlurryNight , just an update: we released v4 which is now called composable-functions and should work just fine with any custom parser. Zod is no longer a dependency.

We prepared some instructions and an example which uses @arktypeio/arktype :
https://github.com/seasonedcc/composable-functions/blob/main/examples/arktype/README.md

**Comment by FlurryNight** [comment]
> Hey @marcus-sa and @FlurryNight , just an update: we released v4 which is now called composable-functions and should work just fine with any custom parser. Zod is no longer a dependency.
> 
> We prepared some instructions and an example which uses @arktypeio/arktype :
> https://github.com/seasonedcc/composable-functions/blob/main/examples/arktype/README.md

Hey, awesome. nice work
Thanks for the info
