### ISSUE TITLE
Is there a way to handle multipart forms? With file uploads?

### ISSUE THREAD

**Issue by mcbergsma** [seasonedcc/composable-functions#34]
Title says it all. I've got a couple small apps that this could be really useful for, but one of them requires a user to upload a file. It was a bit messy getting file uploads working in Remix to begin with, so I want to know if this package has a way of handling them before going down that path.

**Comment by gustavoguichard** [comment]
Hi @mcbergsma,
We think multipart or any form enctype is not domain language but UI/controller responsibility that said you need to do something in your action to transform the data in something that can be parseable by zod.

Following [remix docs](https://remix.run/docs/en/v1/api/remix#unstable_parsemultipartformdata) you'll realize the `unstable_parseMultipartFormData` returns `FormData` and the file will be a string if you turn it into a base64 inside the uploadHandler.

Then you can pass it to our [`inputFromFormData`](https://github.com/SeasonedSoftware/remix-domains#inputfromformdata) and let zod check for the string.

Here is an example of an uploadHandler that'd turn the uploaded file into a base64 string:

```ts
import type { UploadHandler } from '@remix-run/node/formData'

function base64UploadHandler(inputName: string): UploadHandler {
  return async ({ name, stream }) => {
    if (name === inputName) {
      const chunks: Uint8Array[] = []
      for await (let chunk of stream) chunks.push(chunk)

      stream.resume()
      return Buffer.concat(chunks).toString('base64')
    }
  }
}

export { base64UploadHandler }
```

Your action would look something like:
```ts
export async function action({ request }: ActionArgs) {
  const uploadHandler: UploadHandler = base64UploadHandler('image')
  const formData = await unstable_parseMultipartFormData(request, uploadHandler)
  const result = await updateUserProfile(inputFromFormData(formData))
  if (!result.success) return result

  return redirect('/success-path')
}
```

I hope it helps!

I'll be closing this issue for now, feel free to bring more issues/questions ;)
